main_factions = Factions
main_persons = People
main_districts = Districts
main_item_faction = Faction
main_item_person = Person
main_item_district = District
menu = Menu
menu_restart = Restart
menu_settings = Settings
menu_exit = Exit
about = About
app_error_err = Error: {$err}
version_ver = version: {$ver}
changenotes = Change Notes
app_starting = Starting
app_ready = Ready
app_edit_itm = Editing {$itm}
app_add_itm = Add New {$itm}
app_create_itm = Creating New {$itm}
name_heading = Name
tier_heading = Tier
hq_heading = HQ
description_heading = Description
notes_heading = Notes
wealth_heading = Wealth
safety_heading = Safety
crime_heading = Crime
occult_heading = Occult
turf_heading = Turf
edit_save = Save
